language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t aglebionek/frontend -f ./frontend/Dockerfile.dev .

script:
  - docker run -e CI=true aglebionek/frontend npm run test