apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  REDIS_HOST: redis-cluster-ip
  REDIS_PORT: '6379'
  PG_DATABASE: postgres
  PG_HOST: postgres-cluster-ip
  PG_USER: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: BASE64_ENCODED_PASSWORD
