apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  templates:
    containers:
      - name: worker
        image: stephengrider/multi-worker