FROM alpine:latest

RUN addgroup -S node && adduser -S node -G node
RUN apk add --no-cache npm

USER node

 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "run", "start"]