# https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-to-google-kubernetes-engine (source to rework the workflow)
name: 16 - Kubernetes Production Deployment on GKE
on:
  push:
    branches:
      - master
    paths:
      - '16-section/**'

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the dev image and run tests
        run: |
          cd 16-section
          docker build -t aglebionek/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true aglebionek/react-test npm test

      - name: Set Service Key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # - name: Set Project
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     project_id: 

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: multi-cluster
          location: europe-central2-b

      - name: Build production images
        run: |
          cd 16-section
          mkdir ./server/certs
          echo "${{ secrets.POSTGRES_CERT }}" > ./server/certs/ca-certificate.crt
          docker build -t aglebionek/section-16-client:latest -t aglebionek/section-16-client:${{ env.SHA }} ./client
          docker build -t aglebionek/section-16-server:latest -t aglebionek/section-16-server:${{ env.SHA }} ./server
          docker build -t aglebionek/section-16-worker:latest -t aglebionek/section-16-worker:${{ env.SHA }} ./worker

      - name: Log in to Docker Hub and push production images
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          docker push aglebionek/section-16-client:latest
          docker push aglebionek/section-16-server:latest
          docker push aglebionek/section-16-worker:latest

          docker push aglebionek/section-16-client:${{ env.SHA }}
          docker push aglebionek/section-16-server:${{ env.SHA }}
          docker push aglebionek/section-16-worker:${{ env.SHA }}

      - name: Apply
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_BASE64 }}
        run: |
          cd 16-section
          sed -i "s/POSTGRES_PASSWORD: BASE64_ENCODED_PASSWORD/POSTGRES_PASSWORD: $POSTGRES_PASSWORD/" ./_k8s/.envs.yml

          kubectl apply -f ./_k8s
          kubectl set image deployments/client-deployment client=aglebionek/section-16-client:${{ env.SHA }}
          kubectl set image deployments/server-deployment server=aglebionek/section-16-server:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=aglebionek/section-16-worker:${{ env.SHA }}
