name: Build, test and deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
    paths:
      - '7-section/**'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the dev image and run tests
        run: |
          cd 7-section
          docker build -f Dockerfile.dev . -t aglebionek/docker-course-section-7:dev
          docker run -e CI=true aglebionek/docker-course-section-7:dev npm run test

      - name: Generate deployment zip package
        run: |
          cd 7-section
          zip -r ../deploy.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: section-7
          environment_name: Section-7-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-343218192670
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip