name: Build, test and deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
    paths:
      - '7-section/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub, build the image and run tests
        run: |
          cd 7-section
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile.dev . -t @aglebionek/docker-course-section-7
          docker run -e CI=true @aglebionek/docker-course-section-7 npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to AWS Elastic Beanstalk
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-gh
      #     environment_name: Dockergh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
